version: '3.8'

networks:
  main-network:
    external: true
    # name: main-network
services:
  backend:
    depends_on:
      - redis
    hostname: backend
    build: .
    ports:
        - "8090:8090"
    expose:
        - 8099
    volumes:
        - ".:/home/app"
    command: ./actix-scaffolding
    networks:
        - main-network
    env_file:
        - .env
    environment:
      - STAGE=PRODUCTION
    logging:
        driver: "json-file"
        options:
            max-size: "50m"
    
  redis:
    image: redis:latest
    ports:
      - "6378:6378"
    expose:
      - "6378"
    networks:
      - main-network
    volumes:
      - redis-data:/data
    command: redis-server --save 20 1 --loglevel warning --port 6378
    logging:
      driver: "json-file"
      options:
          max-size: "50m"
volumes:
  redis-data:
